<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TECD7PI" failures="2" tests="13" name="Default test" time="226.677" errors="0" timestamp="2025-04-22T11:21:16 IST">
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgTest" time="14.47"/>
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithIndAndType" time="16.427">
    <skipped/>
  </testcase> <!-- createOrgWithIndAndType -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithIndAndType" time="16.276">
    <skipped/>
  </testcase> <!-- createOrgWithIndAndType -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithIndAndType" time="16.398">
    <skipped/>
  </testcase> <!-- createOrgWithIndAndType -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithIndAndType" time="16.123">
    <skipped/>
  </testcase> <!-- createOrgWithIndAndType -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithIndAndType" time="18.109">
    <skipped/>
  </testcase> <!-- createOrgWithIndAndType -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithIndAndType" time="17.937">
    <failure type="org.openqa.selenium.NoSuchElementException" message="Cannot locate option with value: Electronics3784
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.27.0&amp;apos;, revision: &amp;apos;d6e718d134&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;23.0.1&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate option with value: Electronics3784
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.1'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.Select.findOptionsByValue(Select.java:393)
at org.openqa.selenium.support.ui.Select.selectByValue(Select.java:277)
at GenericUtilities.WebDriver_Utility.HandleDropdownUsingValue(WebDriver_Utility.java:60)
at Organization_ModuleTest.CreateNewOrgTest.createOrgWithIndAndType(CreateNewOrgTest.java:173)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- createOrgWithIndAndType -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithPhnNoTest" time="11.85">
    <skipped/>
  </testcase> <!-- createOrgWithPhnNoTest -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithPhnNoTest" time="9.137">
    <skipped/>
  </testcase> <!-- createOrgWithPhnNoTest -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithPhnNoTest" time="9.2">
    <skipped/>
  </testcase> <!-- createOrgWithPhnNoTest -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithPhnNoTest" time="8.951">
    <skipped/>
  </testcase> <!-- createOrgWithPhnNoTest -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithPhnNoTest" time="8.937">
    <skipped/>
  </testcase> <!-- createOrgWithPhnNoTest -->
  <testcase classname="Organization_ModuleTest.CreateNewOrgTest" name="createOrgWithPhnNoTest" time="9.519">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at Organization_ModuleTest.CreateNewOrgTest.createOrgWithPhnNoTest(CreateNewOrgTest.java:121)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- createOrgWithPhnNoTest -->
</testsuite> <!-- Default test -->
