<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TECD7PI" failures="0" tests="2" name="Organization_ModuleTest.CreateOrgWithPhoneNumberTest" time="0.042" errors="1" timestamp="2025-04-21T14:45:08 IST" skipped="1">
  <testcase classname="Organization_ModuleTest.CreateOrgWithPhoneNumberTest" name="beforeSuit" time="0.041">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&quot; because the return value of &quot;GenericUtilities.ClassObject_Utility.getTest()&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "GenericUtilities.ClassObject_Utility.getTest()" is null
at BaseclassUtility.Baseclass.beforeSuit(Baseclass.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:358)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
    <system-out>
      <![CDATA[Configure the DB:Connect]]>
    </system-out>
  </testcase> <!-- beforeSuit -->
  <testcase classname="Organization_ModuleTest.CreateOrgWithPhoneNumberTest" name="createOrgWithIndAndType" time="0.001">
    <skipped/>
  </testcase> <!-- createOrgWithIndAndType -->
  <system-out>
    <![CDATA[Configure the DB:Connect]]>
  </system-out>
</testsuite> <!-- Organization_ModuleTest.CreateOrgWithPhoneNumberTest -->
